// Multi-target code generation (PLAN §22). Phase 1: blocks -> Python.
// Every example must produce syntactically valid Python; the algorithmic
// examples must also run and give the right answer.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import SB3Creator from '../src/utils/sb3Creator.js';
import examples from '../src/utils/examples.js';

function pythonCmd() {
    for (const cmd of ['python3', 'python']) {
        try { execFileSync(cmd, ['--version'], { stdio: 'ignore' }); return cmd; } catch { /* next */ }
    }
    return null;
}
const PY = pythonCmd();
const dir = mkdtempSync(path.join(tmpdir(), 'bw-py-'));

for (const [name, code] of Object.entries(examples)) {
    test(`python codegen: ${name} generates valid Python`, () => {
        const c = new SB3Creator();
        c.parse(code);
        const py = c.generatePython();
        assert.ok(py.length > 20, 'non-empty output');
        assert.ok(py.startsWith('# Generated by Brickwright'), 'has header');
        if (PY) {
            const file = path.join(dir, `${name}.py`);
            writeFileSync(file, py);
            // py_compile throws on a syntax error -> fails the test with its message.
            execFileSync(PY, ['-m', 'py_compile', file]);
        }
    });
}

test('python codegen: the quiz is readable, runnable, and correct', () => {
    const c = new SB3Creator();
    c.parse(examples.educational);
    const py = c.generatePython();
    assert.match(py, /answer = input\(/, 'ask -> input()');
    assert.match(py, /_eq\(answer, 12\)/, 'equality via loose _eq helper');
    assert.match(py, /scratch\.say\((s\d+_)?score\b/, 'say score -> scratch.say (shim prints)');
    assert.match(py, /when_flag_clicked\(\)/, 'flag hat is called');
    if (PY) {
        const file = path.join(dir, 'quiz.py');
        writeFileSync(file, py);
        const out = execFileSync(PY, [file], { input: '12\n32\n' }).toString();
        assert.match(out, /Correct!/);
        assert.match(out.trim().split('\n').pop(), /^2$/, 'final score is 2');
    }
});

test('python codegen: sprite ops become scratch.* calls, list ops become real Python', () => {
    const c = new SB3Creator();
    c.parse(examples.g2048);
    const py = c.generatePython();
    assert.match(py, /\.append\(|\.clear\(\)|\[int\(/, 'list blocks -> Python list ops');
    assert.match(py, /scratch\.\w+\(/, 'sprite/graphics blocks -> reversible scratch.<method>() calls');
    assert.match(py, /scratch\.sprite\(/, 'sprite structure is marked for round-tripping');
});

// ---- JavaScript backend ----------------------------------------------------------

for (const [name, code] of Object.entries(examples)) {
    test(`js codegen: ${name} generates valid JavaScript`, () => {
        const c = new SB3Creator();
        c.parse(code);
        const js = c.generateJavaScript();
        assert.ok(js.startsWith('// Generated by Brickwright'), 'has header');
        // new Function() parses the code (throws SyntaxError on bad output) without running it.
        assert.doesNotThrow(() => new Function(js), 'parses as valid JS');
    });
}

test('js codegen: the quiz runs and scores correctly', () => {
    const c = new SB3Creator();
    c.parse(examples.educational);
    const js = c.generateJavaScript();
    const answers = ['12', '32'];
    let i = 0;
    const logs = [];
    const run = new Function('prompt', 'console', js);
    run(() => answers[i++], { log: (...x) => logs.push(x.join(' ')) });
    assert.equal(logs.filter((l) => l === 'Correct!').length, 2, 'both answers correct');
    assert.equal(logs[logs.length - 1], '2', 'final score is 2');
});
