/* Generated by Brickwright — blocks → C for the STC12 / 8051.
 * Regenerating from the project overwrites this file. Your edits are not
 * stuck here though — the C reader imports this back into blocks, and it
 * names anything it cannot represent rather than dropping it in silence.
 */
/* @bw-begin — machine-readable; do not hand-edit.
 * @bw device eater6502
 * @bw clock 1000000
 * @bw pin sda PA0 output
 * @bw pin scl PA1 output
 * @bw pin led PA2 output
 * @bw pin b0 PB0 input
 * @bw pin b1 PB1 input
 * @bw pin b2 PB2 input
 * @bw pin b3 PB3 input
 * @bw var count "count"
 * @bw script main 0 stage
 * @bw-end */
#include <stdint.h>

#define F_CPU 1000000UL

/* The composable 6502 machine (EATER6502 preset): W65C22 VIA at
 * $6000, W65C51 ACIA at $5000, spelled as addresses from the WDC
 * datasheets. Timer 1 free-runs at LATCH+2 cycles per rollover; the
 * latch below makes that exactly 1 ms at this clock. There is NO
 * interrupt in this build: bw_now() polls the T1 flag (IFR6) and
 * accumulates. cc65-compatible C (C89 declarations, no VLA, no
 * mixed declarations). */
#define BW_VIA(a)  (*(volatile uint8_t *)(0x6000u + (a)))
#define BW_VIA_ORB   BW_VIA(0x0u)
#define BW_VIA_ORA   BW_VIA(0x1u)
#define BW_VIA_DDRB  BW_VIA(0x2u)
#define BW_VIA_DDRA  BW_VIA(0x3u)
#define BW_VIA_T1CL  BW_VIA(0x4u)
#define BW_VIA_T1CH  BW_VIA(0x5u)
#define BW_VIA_ACR   BW_VIA(0xbu)
#define BW_VIA_IFR   BW_VIA(0xdu)
#define BW_VIA_IRB   BW_VIA_ORB
/* Port A reads through $600F: no handshake, so no CA-flag clears. */
#define BW_VIA_IRA   BW_VIA(0xfu)
#define BW_ACIA_DATA   (*(volatile uint8_t *)0x5000u)
#define BW_ACIA_STATUS (*(volatile uint8_t *)0x5001u)
#define BW_ACIA_CMD    (*(volatile uint8_t *)0x5002u)
#define BW_ACIA_CTRL   (*(volatile uint8_t *)0x5003u)
#define BW_T1_LATCH ((uint16_t)(F_CPU / 1000UL - 2UL))

/* No tick ISR on this core either — but unlike the RP2040 there is
 * no free-running microsecond counter to read, so the millisecond
 * count is HARVESTED: T1 rolls over every 1 ms and sets IFR6;
 * bw_now() collects the flag and increments. Tasks yield at every
 * wait and every loop back-edge, and every wait polls, so the poll
 * cadence beats the 1 ms period by construction. (A single block
 * computing for >1 ms between yields would drop a tick — the same
 * class of caveat as the AVR's interrupts-off window, and the
 * corpus shapes stay far under it at this clock.) */
static uint32_t bw_ms;
/* The FLAG-CLEARING read must survive the optimizer: cc65 -O discards
 * a (void)-cast volatile read outright (measured: IFR6 stayed set and
 * bw_ms counted scheduler passes, ~2.4x fast). A store to a volatile
 * sink cannot be dropped. */
static volatile uint8_t bw_t1_sink;

static uint32_t bw_now(void)
{
    if (BW_VIA_IFR & 0x40u) {
        bw_t1_sink = BW_VIA_T1CL;  /* reading T1C-L clears IFR6 */
        ++bw_ms;
    }
    return bw_ms;
}

/* No scheduler in this build; T1 still rolls, so a blocking delay
 * is a wait on the harvested count, never on a cycle count. */
static void delay_ms(uint32_t ms)
{
    uint32_t start = bw_now();
    while ((int32_t)(bw_now() - start - ms) < 0) ;
}

/* ---- device helper stubs (emitted because devices_* blocks are used) ----
 * These are no-ops on the device target. A real implementation would
 * drive the peripheral via its protocol (I2C for LCD, PWM for servo,
 * pin toggling for shift registers, etc.). The stubs make the code
 * compile and record the call for the simulator. */
static void bw_servo_set(int servo, int angle) { /* BW_STUB: devices_setservo — no-op on hardware */ }
static int bw_servo_get(int servo) { /* BW_STUB: devices_servoangle */ return 0; }
static void bw_motor_speed(int motor, int speed) { /* BW_STUB: devices_setmotor — no-op on hardware */ }
static int bw_motor_get_speed(int motor) { /* BW_STUB: devices_motorspeed */ return 0; }
static void bw_motor_dir(int motor, int dir) { /* BW_STUB: devices_setdirection — no-op on hardware */ }
static int bw_motor_get_dir(int motor) { /* BW_STUB: devices_motordirection */ return 0; }
static void bw_relay_set(int relay, int on) { /* BW_STUB: devices_setrelay — no-op on hardware */ }
static void bw_device_activate(int dev) { /* BW_STUB: devices_activate — no-op on hardware */ }
static void bw_device_deactivate(int dev) { /* BW_STUB: devices_deactivate — no-op on hardware */ }
static int bw_energised(int d) { /* BW_STUB: devices_energised */ return 0; }
static int bw_pressed(int btn) { /* BW_STUB: devices_pressed */ return 0; }
static int bw_motion(int s) { /* BW_STUB: devices_motion */ return 0; }
static int bw_tilted(int s) { /* BW_STUB: devices_tilted */ return 0; }
static int bw_temperature(int s) { /* BW_STUB: devices_temperature */ return 0; }
static int bw_light(int s) { /* BW_STUB: devices_light */ return 0; }
static int bw_flex(int s) { /* BW_STUB: devices_flex */ return 0; }
static int bw_force(int s) { /* BW_STUB: devices_force */ return 0; }
static int bw_above(int s, int thr) { /* BW_STUB: devices_above */ return 0; }
static int bw_distance(int s) { /* BW_STUB: devices_distance */ return 0; }
static int bw_closer(int s, int dist) { /* BW_STUB: devices_closer */ return 0; }
static void bw_neopixel_set(int s, int i, int r, int g, int b) { /* BW_STUB: devices_setneopixel — no-op on hardware */ }
static void bw_neopixel_clear(int s) { /* BW_STUB: devices_clearneopixels — no-op on hardware */ }
/* I2C bus: bit-banged via W65C22 VIA port A (shadow-byte RMW). */
#define I2C_SDA_MASK (1u << 0)
#define I2C_SCL_MASK (1u << 1)
static unsigned char _i2c_sh;  /* shadow for BW_VIA_ORA */
#define I2C_SDA_HI() (_i2c_sh |= I2C_SDA_MASK, BW_VIA_ORA = _i2c_sh)
#define I2C_SDA_LO() (_i2c_sh &= (unsigned char)~I2C_SDA_MASK, BW_VIA_ORA = _i2c_sh)
#define I2C_SCL_HI() (_i2c_sh |= I2C_SCL_MASK, BW_VIA_ORA = _i2c_sh)
#define I2C_SCL_LO() (_i2c_sh &= (unsigned char)~I2C_SCL_MASK, BW_VIA_ORA = _i2c_sh)

/* I2C timing: t_LOW ≥ 4.7 µs (100 kHz standard mode). */
static void i2c_delay(void) { unsigned char i; for (i = 0; i < 2; i++) ; }
static void i2c_start(void) { I2C_SDA_HI(); I2C_SCL_HI(); i2c_delay(); I2C_SDA_LO(); i2c_delay(); I2C_SCL_LO(); }
static void i2c_stop(void)  { I2C_SDA_LO(); I2C_SCL_HI(); i2c_delay(); I2C_SDA_HI(); i2c_delay(); }
static void i2c_write(unsigned char dat)
{
    unsigned char i;
    for (i = 0; i < 8; i++) {
        if (dat & 0x80) I2C_SDA_HI(); else I2C_SDA_LO();
        dat <<= 1;
        I2C_SCL_HI(); i2c_delay(); I2C_SCL_LO(); i2c_delay();
    }
    /* ACK clock — we do not check the ACK (write-only devices). */
    I2C_SDA_HI(); I2C_SCL_HI(); i2c_delay(); I2C_SCL_LO(); i2c_delay();
}

static void bw_lcd_print_s(int disp, const char *s) { /* BW_STUB: devices_lcdprint — no-op on hardware */ }
static void bw_lcd_print_n(int disp, long n) { /* BW_STUB: devices_lcdprint — no-op on hardware */ }
static void bw_lcd_cursor(int disp, int row, int col) { /* BW_STUB: devices_lcdcursor — no-op on hardware */ }
static void bw_lcd_clear(int disp) { /* BW_STUB: devices_lcdclear — no-op on hardware */ }
static void bw_tft_pixel(int d, int x, int y, int r, int g, int b) { /* BW_STUB: devices_tftpixel — no-op on hardware */ }
static void bw_tft_fill(int d, int x, int y, int w, int h, int r, int g, int b) { /* BW_STUB: devices_tftfill — no-op on hardware */ }
static void bw_tft_clear(int d) { /* BW_STUB: devices_tftclear — no-op on hardware */ }
static void bw_tft_print_s(int d, const char *s) { /* BW_STUB: devices_tftprint — no-op on hardware */ }
static void bw_tft_print_n(int d, long n) { /* BW_STUB: devices_tftprint — no-op on hardware */ }
static void bw_tft_cursor(int d, int row, int col) { /* BW_STUB: devices_tftcursor — no-op on hardware */ }
/* SSD1306 OLED: 128x64, I2C at 0x3C, page addressing. */
#define OLED_ADDR 0x3C
#define OLED_W    128
#define OLED_H    64
#define OLED_PAGES (OLED_H / 8)

static void oled_cmd(unsigned char cmd)
{
    i2c_start();
    i2c_write((unsigned char)(OLED_ADDR << 1));
    i2c_write(0x00);  /* control: Co=0 D/C#=0 → command */
    i2c_write(cmd);
    i2c_stop();
}

static void oled_data_start(void)
{
    i2c_start();
    i2c_write((unsigned char)(OLED_ADDR << 1));
    i2c_write(0x40);  /* control: Co=0 D/C#=1 → data stream */
}

/* 5x7 font — ASCII 0x20..0x7E (95 printable chars × 5 bytes). */
/* Public domain bitmap (Adafruit GFX lineage). */
static const  unsigned char font5x7[475] = {
    0x00,0x00,0x00,0x00,0x00, 0x00,0x00,0x5F,0x00,0x00,
    0x00,0x07,0x00,0x07,0x00, 0x14,0x7F,0x14,0x7F,0x14,
    0x24,0x2A,0x7F,0x2A,0x12, 0x23,0x13,0x08,0x64,0x62,
    0x36,0x49,0x55,0x22,0x50, 0x00,0x05,0x03,0x00,0x00,
    0x00,0x1C,0x22,0x41,0x00, 0x00,0x41,0x22,0x1C,0x00,
    0x14,0x08,0x3E,0x08,0x14, 0x08,0x08,0x3E,0x08,0x08,
    0x00,0x50,0x30,0x00,0x00, 0x08,0x08,0x08,0x08,0x08,
    0x00,0x60,0x60,0x00,0x00, 0x20,0x10,0x08,0x04,0x02,
    0x3E,0x51,0x49,0x45,0x3E, 0x00,0x42,0x7F,0x40,0x00,
    0x42,0x61,0x51,0x49,0x46, 0x21,0x41,0x45,0x4B,0x31,
    0x18,0x14,0x12,0x7F,0x10, 0x27,0x45,0x45,0x45,0x39,
    0x3C,0x4A,0x49,0x49,0x30, 0x01,0x71,0x09,0x05,0x03,
    0x36,0x49,0x49,0x49,0x36, 0x06,0x49,0x49,0x29,0x1E,
    0x00,0x36,0x36,0x00,0x00, 0x00,0x56,0x36,0x00,0x00,
    0x08,0x14,0x22,0x41,0x00, 0x14,0x14,0x14,0x14,0x14,
    0x00,0x41,0x22,0x14,0x08, 0x02,0x01,0x51,0x09,0x06,
    0x32,0x49,0x79,0x41,0x3E, 0x7E,0x11,0x11,0x11,0x7E,
    0x7F,0x49,0x49,0x49,0x36, 0x3E,0x41,0x41,0x41,0x22,
    0x7F,0x41,0x41,0x22,0x1C, 0x7F,0x49,0x49,0x49,0x41,
    0x7F,0x09,0x09,0x09,0x01, 0x3E,0x41,0x49,0x49,0x7A,
    0x7F,0x08,0x08,0x08,0x7F, 0x00,0x41,0x7F,0x41,0x00,
    0x20,0x40,0x41,0x3F,0x01, 0x7F,0x08,0x14,0x22,0x41,
    0x7F,0x40,0x40,0x40,0x40, 0x7F,0x02,0x0C,0x02,0x7F,
    0x7F,0x04,0x08,0x10,0x7F, 0x3E,0x41,0x41,0x41,0x3E,
    0x7F,0x09,0x09,0x09,0x06, 0x3E,0x41,0x51,0x21,0x5E,
    0x7F,0x09,0x19,0x29,0x46, 0x46,0x49,0x49,0x49,0x31,
    0x01,0x01,0x7F,0x01,0x01, 0x3F,0x40,0x40,0x40,0x3F,
    0x1F,0x20,0x40,0x20,0x1F, 0x3F,0x40,0x38,0x40,0x3F,
    0x63,0x14,0x08,0x14,0x63, 0x07,0x08,0x70,0x08,0x07,
    0x61,0x51,0x49,0x45,0x43, 0x00,0x7F,0x41,0x41,0x00,
    0x02,0x04,0x08,0x10,0x20, 0x00,0x41,0x41,0x7F,0x00,
    0x04,0x02,0x01,0x02,0x04, 0x40,0x40,0x40,0x40,0x40,
    0x00,0x01,0x02,0x04,0x00, 0x20,0x54,0x54,0x54,0x78,
    0x7F,0x48,0x44,0x44,0x38, 0x38,0x44,0x44,0x44,0x20,
    0x38,0x44,0x44,0x48,0x7F, 0x38,0x54,0x54,0x54,0x18,
    0x08,0x7E,0x09,0x01,0x02, 0x0C,0x52,0x52,0x52,0x3E,
    0x7F,0x08,0x04,0x04,0x78, 0x00,0x44,0x7D,0x40,0x00,
    0x20,0x40,0x44,0x3D,0x00, 0x7F,0x10,0x28,0x44,0x00,
    0x00,0x41,0x7F,0x40,0x00, 0x7C,0x04,0x18,0x04,0x78,
    0x7C,0x08,0x04,0x04,0x78, 0x38,0x44,0x44,0x44,0x38,
    0x7C,0x14,0x14,0x14,0x08, 0x08,0x14,0x14,0x18,0x7C,
    0x7C,0x08,0x04,0x04,0x08, 0x48,0x54,0x54,0x54,0x20,
    0x04,0x3F,0x44,0x40,0x20, 0x3C,0x40,0x40,0x20,0x7C,
    0x1C,0x20,0x40,0x20,0x1C, 0x3C,0x40,0x30,0x40,0x3C,
    0x44,0x28,0x10,0x28,0x44, 0x0C,0x50,0x50,0x50,0x3C,
    0x44,0x64,0x54,0x4C,0x44, 0x00,0x08,0x36,0x41,0x00,
    0x00,0x00,0x7F,0x00,0x00, 0x00,0x41,0x36,0x08,0x00,
    0x10,0x08,0x08,0x10,0x08
};

static void oled_set_page_col(unsigned char page, unsigned char col)
{
    oled_cmd((unsigned char)(0xB0 | (page & 0x07)));
    oled_cmd((unsigned char)(0x00 | (col & 0x0F)));
    oled_cmd((unsigned char)(0x10 | ((col >> 4) & 0x0F)));
}

static void bw_oled_clear(int disp)
{
    unsigned int i;
    (void)disp;
    /* Horizontal mode for bulk write, then back to page mode. */
    oled_cmd(0x20); oled_cmd(0x00);  /* horizontal addressing */
    oled_cmd(0x21); oled_cmd(0x00); oled_cmd(0x7F);  /* col 0-127 */
    oled_cmd(0x22); oled_cmd(0x00); oled_cmd(0x07);  /* page 0-7 */
    oled_data_start();
    for (i = 0; i < 1024; i++) i2c_write(0x00);
    i2c_stop();
    oled_cmd(0x20); oled_cmd(0x02);  /* back to page mode */
    oled_set_page_col(0, 0);
}

static void bw_oled_pixel(int disp, int x, int y, int val)
{
    unsigned char page = (unsigned char)(y >> 3);
    unsigned char bit  = (unsigned char)(1 << (y & 7));
    (void)disp;
    oled_set_page_col(page, (unsigned char)x);
    oled_data_start();
    i2c_write(val ? bit : 0x00);
    i2c_stop();
}

static void oled_putchar(unsigned char c)
{
    unsigned char i;
    unsigned int idx;
    if (c < 0x20 || c > 0x7E) c = 0x20;
    idx = (unsigned int)(c - 0x20) * 5;
    oled_data_start();
    for (i = 0; i < 5; i++) i2c_write(font5x7[idx + i]);
    i2c_write(0x00);  /* 1-pixel gap */
    i2c_stop();
}

static void bw_oled_print_s(int disp, const char *s)
{
    (void)disp;
    while (*s) oled_putchar((unsigned char)*s++);
}

static void bw_oled_print_n(int disp, long n)
{
    char buf[12]; unsigned char i = 0; unsigned long u;
    (void)disp;
    if (n < 0) { oled_putchar(0x2D); u = (unsigned long)(-n); }
    else u = (unsigned long)n;
    if (u == 0) { oled_putchar(0x30); return; }
    while (u) { buf[i++] = (char)(0x30 + (u % 10)); u /= 10; }
    while (i) oled_putchar((unsigned char)buf[--i]);
}

static void bw_oled_cursor(int disp, int row, int col)
{
    (void)disp;
    oled_set_page_col((unsigned char)(row & 0x07), (unsigned char)(col * 6));
}

static int bw_device_state(int dev) { (void)dev; return 0; }
static void bw_7seg_show(int disp, int digit) { /* BW_STUB: devices_showdigit — no-op on hardware */ }
static void bw_rgb_set(int led, int r, int g, int b) { /* BW_STUB: devices_setrgb — no-op on hardware */ }
static void bw_matrix_set(int m, int x, int y, int br) { /* BW_STUB: devices_setpixel — no-op on hardware */ }
static void bw_matrix_clear(int m) { /* BW_STUB: devices_clearmatrix — no-op on hardware */ }
static int bw_ir_code(int s) { /* BW_STUB: devices_ircode */ return 0; }

/* Variables: long, matching Scratch's number range — int is 16-bit on
 * sdcc/avr-gcc/cc65 and silently wraps mid-expression (76-multimeter). */
static long count = 0;

/* Register setup: ports, ADC, Timer 0. Kept out of main() so the program
 * body stands alone — a C -> blocks reader can then tell them apart. */
static void bw_setup(void)
{
    BW_VIA_ORA &= (uint8_t)~(1 << 0);      /* sda: start OFF */
    BW_VIA_DDRA |= (uint8_t)(1 << 0);   /* sda = PA0 output */
    BW_VIA_ORA &= (uint8_t)~(1 << 1);      /* scl: start OFF */
    BW_VIA_DDRA |= (uint8_t)(1 << 1);   /* scl = PA1 output */
    BW_VIA_ORA &= (uint8_t)~(1 << 2);      /* led: start OFF */
    BW_VIA_DDRA |= (uint8_t)(1 << 2);   /* led = PA2 output */
    BW_VIA_ACR = 0x40;             /* Timer 1 free-run */
    BW_VIA_T1CL = (uint8_t)(BW_T1_LATCH & 0xffu);
    BW_VIA_T1CH = (uint8_t)(BW_T1_LATCH >> 8);   /* load + start */
}

int main(void)
{
    bw_setup();

    bw_oled_clear(1);
    bw_oled_print_s(1, "6502 CALC");
    count = 0;
    for (;;) {
        bw_oled_cursor(1, 1, 0);
        if ((((BW_VIA_IRB >> 0) & 1) > 0)) {
            count += 1;
        }
        if ((((BW_VIA_IRB >> 1) & 1) > 0)) {
            count += -1;
        }
        if ((((BW_VIA_IRB >> 2) & 1) > 0)) {
            count = 0;
        }
        bw_oled_print_n(1, count);
        BW_VIA_ORA |= (uint8_t)(1 << 2);
        delay_ms(100);
        BW_VIA_ORA &= (uint8_t)~(1 << 2);
        delay_ms(100);
    }
}
